import { useEffect } from "react";
import { useNavigate, Link } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import {
  ArrowRight,
  Zap,
  Layout,
  Rocket,
  Star,
  Check,
  ChevronDown,
  Settings,
  FileText,
  MonitorSmartphone,
  Code2,
  Globe,
  Cpu,
} from "lucide-react";
import heroDashboard from "@/assets/hero-dashboard.png";
import { useState } from "react";

const MARQUEE_ITEMS = [
  { icon: Cpu, label: "AI Powered App" },
  { icon: MonitorSmartphone, label: "Internal Tools" },
  { icon: Layout, label: "Admin Panels" },
  { icon: Code2, label: "CRUD Apps" },
  { icon: FileText, label: "Form Builder" },
  { icon: Globe, label: "SaaS" },
];

const FEATURES = [
  {
    tag: "CUSTOMIZE WITH EASE",
    title: "Site Settings — Customization Options",
    desc: "Fine-tune every detail of your website with flexible settings and easy-to-use customization options.",
    icon: Settings,
  },
  {
    tag: "CHOOSE WHAT MATTERS",
    title: "Core Page Selection",
    desc: "Quickly choose and manage the essential pages your website needs — all in one simple place.",
    icon: FileText,
  },
  {
    tag: "BUILD IN ONE CLICK",
    title: "Start Site Generation",
    desc: "Launch your website instantly with smart, automated site generation — no coding or setup required.",
    icon: Rocket,
  },
];

const STEPS = [
  { num: "01", title: "Sign Up", desc: "Create your account in seconds and access all the tools you need to start building." },
  { num: "02", title: "Config Sites", desc: "Set up your site preferences, core pages, and essential details with simple guided options." },
  { num: "03", title: "Start Generating", desc: "Use intuitive no-code tools to design, customize, and launch your website instantly." },
];

const REVIEWS = [
  { name: "Aisha Rahman", role: "Startup Founder", initials: "AR", text: "WebAI helped me launch a complete website in under an hour. The AI-generated design was clean, modern, and required almost no changes." },
  { name: "Kevin Patel", role: "Digital Marketer", initials: "KP", text: "This platform saves me so much time. I can create landing pages for campaigns instantly without depending on designers or developers." },
  { name: "Rafiul Hasan", role: "Web Developer", initials: "RH", text: "WebAI is a game-changer. It speeds up my workflow, gives me ready-made layouts, and makes client projects much easier to deliver." },
  { name: "Sophia Martinez", role: "Business Owner", initials: "SM", text: "I built my business website with zero technical knowledge. WebAI made everything simple and hassle-free." },
  { name: "Liam Anderson", role: "Content Creator", initials: "LA", text: "I love how quickly I can generate full pages. The AI suggestions are accurate, and the editor is super easy to use." },
  { name: "Zara Hossain", role: "E-commerce Entrepreneur", initials: "ZH", text: "WebAI helped me create a professional e-commerce site without hiring a developer. It's fast, intuitive, and perfect for growing brands." },
];

const PRICING = [
  {
    name: "Starter",
    desc: "Perfect for personal projects and getting started.",
    price: "$9",
    features: ["3 AI Website Generations", "Basic Templates", "Community Support", "1 Custom Domain", "Basic Analytics"],
    popular: false,
  },
  {
    name: "Professional",
    desc: "Best for freelancers and growing businesses.",
    price: "$29",
    features: ["Unlimited AI Generations", "Premium Templates", "Priority Support", "5 Custom Domains", "Advanced Analytics", "API Access", "Remove Branding"],
    popular: true,
  },
  {
    name: "Enterprise",
    desc: "For teams and organizations at scale.",
    price: "$99",
    features: ["Everything in Pro", "Dedicated Support", "Unlimited Domains", "Team Collaboration", "SLA Guarantee", "Custom Integrations", "White Label"],
    popular: false,
  },
];

const FAQS = [
  { q: "What is WebAI?", a: "WebAI is an AI-powered no-code website builder that helps you create fully designed, responsive websites in minutes — without any coding or design skills." },
  { q: "Do I need technical knowledge to use WebAI?", a: "No! WebAI is designed for everyone. You can build stunning websites without writing a single line of code." },
  { q: "Can I edit the AI-generated website?", a: "Yes, you have full control to edit, customize, and adjust any part of the generated website to match your vision." },
  { q: "Is the website mobile-friendly?", a: "Absolutely. All websites generated by WebAI are fully responsive and optimized for mobile, tablet, and desktop." },
  { q: "Can I publish my website with WebAI?", a: "Yes, you can publish your website directly through our platform with your own custom domain." },
];

const Index = () => {
  const navigate = useNavigate();
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const [billingCycle, setBillingCycle] = useState<"monthly" | "yearly">("monthly");

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      if (session) {
        navigate("/dashboard");
      }
    });
  }, [navigate]);

  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Navbar */}
      <nav className="fixed top-0 left-0 right-0 z-50 border-b border-border/50 bg-background/80 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center">
              <Zap className="h-5 w-5 text-primary-foreground" />
            </div>
            <span className="text-xl font-bold font-display">
              Web<span className="text-primary">AI</span>
            </span>
          </Link>
          <div className="hidden md:flex items-center gap-8 text-sm text-muted-foreground">
            <a href="#features" className="hover:text-foreground transition-colors">Features</a>
            <a href="#pricing" className="hover:text-foreground transition-colors">Pricing</a>
            <a href="#faq" className="hover:text-foreground transition-colors">FAQ</a>
            <a href="#contact" className="hover:text-foreground transition-colors">Contact</a>
          </div>
          <div className="flex items-center gap-3">
            <Link to="/dashboard" className="text-sm text-muted-foreground hover:text-foreground transition-colors hidden md:block">
              Admin
            </Link>
            <Link to="/">
              <Button size="sm" className="bg-primary text-primary-foreground hover:bg-primary/90 rounded-full px-5">
                Login
              </Button>
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="pt-32 pb-16 px-6 text-center">
        <p className="text-xs tracking-[0.3em] uppercase text-primary font-semibold mb-6">
          More Than A Platform
        </p>
        <h1 className="text-5xl md:text-7xl font-bold font-display leading-tight max-w-4xl mx-auto">
          AI That Builds{" "}
          <span className="bg-clip-text text-transparent bg-gradient-to-r from-primary to-accent">
            With You
          </span>
        </h1>
        <p className="mt-6 text-muted-foreground max-w-2xl mx-auto text-lg leading-relaxed">
          Work with an AI builder that understands your ideas, writes clean code, and turns them into real products in minutes — from quick prototypes to full-stack apps.
        </p>
        <div className="mt-8 flex items-center justify-center gap-4">
          <Link to="/">
            <Button className="bg-primary text-primary-foreground hover:bg-primary/90 rounded-full px-8 h-12 text-base">
              Get Started
            </Button>
          </Link>
          <a href="#pricing">
            <Button variant="outline" className="rounded-full px-8 h-12 text-base border-border text-foreground hover:bg-secondary gap-2">
              See Pricing <ArrowRight className="h-4 w-4" />
            </Button>
          </a>
        </div>
      </section>

      {/* Marquee */}
      <section className="py-6 overflow-hidden">
        <div className="flex animate-marquee whitespace-nowrap">
          {[...MARQUEE_ITEMS, ...MARQUEE_ITEMS].map((item, i) => (
            <div key={i} className="mx-4 flex items-center gap-2 px-5 py-2.5 rounded-full border border-border bg-secondary/50 text-sm text-muted-foreground shrink-0">
              <item.icon className="h-4 w-4 text-primary" />
              {item.label}
            </div>
          ))}
        </div>
      </section>

      {/* Hero Image */}
      <section className="max-w-6xl mx-auto px-6 pb-20">
        <div className="rounded-2xl overflow-hidden border border-border shadow-2xl shadow-primary/10">
          <img src={heroDashboard} alt="WebAI Dashboard - AI Website Builder Interface" className="w-full" loading="lazy" />
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <p className="text-xs tracking-[0.3em] uppercase text-primary font-semibold text-center mb-3">Core Feature</p>
          <h2 className="text-3xl md:text-5xl font-bold font-display text-center max-w-3xl mx-auto">
            Core Features That Empower{" "}
            <span className="text-primary">Every Creator</span>
          </h2>
          <p className="text-muted-foreground text-center mt-4 max-w-xl mx-auto">
            Everything you need to build beautiful websites fast, simple, and without any code.
          </p>
          <div className="grid md:grid-cols-3 gap-6 mt-14">
            {FEATURES.map((f, i) => (
              <div key={i} className="glass-card rounded-2xl p-8 hover:border-primary/30 transition-all duration-300 group">
                <p className="text-xs tracking-wider uppercase text-primary font-semibold mb-4">{f.tag}</p>
                <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center mb-5 group-hover:bg-primary/20 transition-colors">
                  <f.icon className="h-6 w-6 text-primary" />
                </div>
                <h3 className="text-xl font-bold font-display mb-3">{f.title}</h3>
                <p className="text-muted-foreground text-sm leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <p className="text-xs tracking-[0.3em] uppercase text-primary font-semibold text-center mb-3">How It Works</p>
          <h2 className="text-3xl md:text-5xl font-bold font-display text-center max-w-3xl mx-auto">
            Get Your Site Ready{" "}
            <span className="text-primary">in Minutes</span>
          </h2>
          <p className="text-muted-foreground text-center mt-4 max-w-xl mx-auto">
            Follow three simple steps — sign up, configure your site, and start generating.
          </p>
          <div className="grid md:grid-cols-3 gap-8 mt-14">
            {STEPS.map((s, i) => (
              <div key={i} className="text-center">
                <span className="text-5xl font-bold font-display text-primary/20">{s.num}</span>
                <h3 className="text-xl font-bold font-display mt-4 mb-3">{s.title}</h3>
                <p className="text-muted-foreground text-sm leading-relaxed">{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Reviews */}
      <section className="py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <p className="text-xs tracking-[0.3em] uppercase text-primary font-semibold text-center mb-3">Reviews</p>
          <h2 className="text-3xl md:text-5xl font-bold font-display text-center max-w-3xl mx-auto">
            Trusted by Founders and{" "}
            <span className="text-primary">Developers Worldwide</span>
          </h2>
          <p className="text-muted-foreground text-center mt-4 max-w-xl mx-auto">
            Our platform helps you build faster, launch confidently, and scale with ease.
          </p>
          <div className="grid md:grid-cols-3 gap-6 mt-14">
            {REVIEWS.map((r, i) => (
              <div key={i} className="glass-card rounded-2xl p-6">
                <div className="flex gap-1 mb-4">
                  {[...Array(5)].map((_, j) => (
                    <Star key={j} className="h-4 w-4 fill-primary text-primary" />
                  ))}
                </div>
                <p className="text-sm text-muted-foreground leading-relaxed mb-6">"{r.text}"</p>
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full bg-primary/20 flex items-center justify-center text-sm font-bold text-primary">
                    {r.initials}
                  </div>
                  <div>
                    <p className="text-sm font-semibold">{r.name}</p>
                    <p className="text-xs text-muted-foreground">{r.role}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <p className="text-xs tracking-[0.3em] uppercase text-primary font-semibold text-center mb-3">Pricing</p>
          <h2 className="text-3xl md:text-5xl font-bold font-display text-center max-w-3xl mx-auto">
            Transparent Pricing for{" "}
            <span className="text-primary">Every User</span>
          </h2>
          <p className="text-muted-foreground text-center mt-4 max-w-xl mx-auto">
            Get clear, upfront pricing with no hidden fees or surprises.
          </p>
          <div className="flex justify-center mt-8">
            <div className="flex items-center gap-2 bg-secondary rounded-full p-1">
              <button
                onClick={() => setBillingCycle("monthly")}
                className={`px-5 py-2 rounded-full text-sm font-medium transition-colors ${billingCycle === "monthly" ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:text-foreground"}`}
              >
                Monthly
              </button>
              <button
                onClick={() => setBillingCycle("yearly")}
                className={`px-5 py-2 rounded-full text-sm font-medium transition-colors ${billingCycle === "yearly" ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:text-foreground"}`}
              >
                Yearly
              </button>
            </div>
          </div>
          <div className="grid md:grid-cols-3 gap-6 mt-12">
            {PRICING.map((p, i) => (
              <div key={i} className={`glass-card rounded-2xl p-8 relative ${p.popular ? "border-primary/50 ring-1 ring-primary/20" : ""}`}>
                {p.popular && (
                  <span className="absolute -top-3 left-1/2 -translate-x-1/2 bg-primary text-primary-foreground text-xs font-semibold px-4 py-1 rounded-full">
                    Most Popular
                  </span>
                )}
                <h3 className="text-xl font-bold font-display">{p.name}</h3>
                <p className="text-sm text-muted-foreground mt-2">{p.desc}</p>
                <p className="text-4xl font-bold font-display mt-6">
                  {p.price}
                  <span className="text-base font-normal text-muted-foreground">/month</span>
                </p>
                <Button className={`w-full mt-6 rounded-full h-11 ${p.popular ? "bg-primary text-primary-foreground hover:bg-primary/90" : "bg-secondary text-foreground hover:bg-secondary/80"}`}>
                  Get Started
                </Button>
                <ul className="mt-6 space-y-3">
                  {p.features.map((f, j) => (
                    <li key={j} className="flex items-center gap-2 text-sm text-muted-foreground">
                      <Check className="h-4 w-4 text-primary shrink-0" />
                      {f}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="py-20 px-6">
        <div className="max-w-3xl mx-auto">
          <p className="text-xs tracking-[0.3em] uppercase text-primary font-semibold text-center mb-3">Quick Answers</p>
          <h2 className="text-3xl md:text-5xl font-bold font-display text-center">
            Frequently Asked Questions
          </h2>
          <div className="mt-12 space-y-3">
            {FAQS.map((faq, i) => (
              <div key={i} className="glass-card rounded-xl overflow-hidden">
                <button
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                  className="w-full flex items-center justify-between p-5 text-left"
                >
                  <span className="font-medium">{faq.q}</span>
                  <ChevronDown className={`h-5 w-5 text-muted-foreground transition-transform ${openFaq === i ? "rotate-180" : ""}`} />
                </button>
                {openFaq === i && (
                  <div className="px-5 pb-5 text-sm text-muted-foreground leading-relaxed">
                    {faq.a}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section id="contact" className="py-20 px-6">
        <div className="max-w-4xl mx-auto text-center glass-card rounded-3xl p-16">
          <p className="text-xs tracking-[0.3em] uppercase text-primary font-semibold mb-3">Take Action</p>
          <h2 className="text-3xl md:text-5xl font-bold font-display">Start Building</h2>
          <p className="text-muted-foreground mt-4 max-w-xl mx-auto">
            Join us today and experience the next generation of productivity tools. Sign up now and unlock your potential!
          </p>
          <div className="mt-8 flex justify-center gap-4">
            <Link to="/">
              <Button className="bg-primary text-primary-foreground hover:bg-primary/90 rounded-full px-8 h-12 text-base">
                Get Started Free
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border py-10 px-6">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-primary flex items-center justify-center">
              <Zap className="h-4 w-4 text-primary-foreground" />
            </div>
            <span className="font-bold font-display">Web<span className="text-primary">AI</span></span>
          </div>
          <p className="text-sm text-muted-foreground">© 2026 WebAI. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
};

export default Index;
